Debug pipeline

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -46,7 +46,31 @@ jobs:
 
       - name: Run Swagger coverage
         if: always()
-        run: .swagger-coverage-commandline/swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i target/swagger-coverage-output
+        run: |
+          mkdir -p target/swagger-coverage-output
+          .swagger-coverage-commandline/swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline \
+          -s http://localhost:4111/v3/api-docs \
+          -i target/swagger-coverage-output \
+          --json target/swagger-coverage-output/coverage.json
+        #.swagger-coverage-commandline/swagger-coverage-commandline-1.5.0/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i target/swagger-coverage-output
+
+      - name: Check API coverage (Quality Gate)
+        if: always()
+        run: |
+          THRESHOLD=50
+          FILE="target/swagger-coverage-output/coverage.json"
+          if [ ! -f "$FILE" ]; then
+            echo "❌ Coverage file not found: $FILE"
+            exit 1
+          fi
+          COVERAGE=$(jq '.statistic.percent' "$FILE")
+          echo "📊 API Coverage: ${COVERAGE}%"
+          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
+            echo "🚫 Quality gate failed — coverage below ${THRESHOLD}%"
+            exit 1
+          else
+            echo "✅ Coverage OK"
+          fi
 
       - name: Load test report history
         uses: actions/checkout@v2
@@ -62,24 +86,6 @@ jobs:
           gh_pages: gh-pages
           allure_results: target/allure-results
           allure_history: allure-history
-
-      - name: Check API coverage (Quality Gate)
-        if: always()
-        run: |
-          THRESHOLD=50
-          FILE="allure-report/widgets/coverage.json"
-          if [ ! -f "$FILE" ]; then
-            echo "❌ Coverage file not found: $FILE"
-            exit 1
-          fi
-          COVERAGE=$(jq '.statistic.percent' "$FILE")
-          echo "📊 API Coverage: ${COVERAGE}%"
-          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
-            echo "🚫 Quality gate failed — coverage below ${THRESHOLD}%"
-            exit 1
-          else
-            echo "✅ Coverage OK"
-          fi
 
       - name: Fix permissions for allure-history
         if: always()
