Debug pipeline

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -77,6 +77,14 @@ jobs:
           cp swagger-coverage-report.html allure-history/swagger-coverage/index.html
           cp allure-plugins/swagger-coverage/plugin.json allure-history/swagger-coverage/plugin.json
 
+      - name: Debug list report files
+        if: always()
+        run: |
+          echo "=== Plugin folder structure ==="
+          ls -R allure-history | head -n 50
+          echo "=== Plugin JSON ==="
+          cat allure-history/swagger-coverage/plugin.json || echo "plugin.json not found"
+
       ##- name: Build Swagger coverage report
         ##if: always()
         ##run: sudo cp swagger-coverage-report.html allure-history/${{ github.run_number }}
